const {
  fetcher,
  INNERTUBE,
  wiki,
  musicInfo,
  modules,
  version,
  initlog,
  init,
} = require("../libpoketube-initsys.js");
const {
  IsJsonString,
  convert,
  getFirstLine,
  capitalizeFirstLetter,
  turntomins,
  convertLegacy,
  getRandomInt,
  escapeHtml,
  getRandomArbitrary,
} = require("../ptutils/libpt-coreutils.js");
const media_proxy = require("../libpoketube-video.js");
const atmos = require("../../../pokeatmosurls.json");
const config = require("../../../config.json");

const serverGeneration = Date.now().toString(36);
let currentEpoch = Date.now();

function linkify(text) {
  // regular expression to match URLs
  const urlRegex = /(https?:\/\/[^\s]+)/g;

  return text.replace(urlRegex, (url) => {
    // wrap the URL in an <a> tag with the URL as the href attribute
    return `<a href="/api/redirect?u=${btoa(
      url
        .replace(/twitter\.com/g, "nitter.net")
        .replace(/reddit\.com/g, "teddit.net")
        .replace("https://youtube.com", "")
        .replace("https://youtu.be", "")
    )}" target="_blank">${url}</a>`;
  });
}

function channelurlfixer(text) {
  // Create a regular expression to match <a> tags with href containing "/channel/"
  const regex = /<a\s+href="\/channel\/([^"]+)"/g;
  // Replace matching <a> tags with the modified href attribute
  const updatedDescription = text.replace(regex, '<a href="/channel?id=$1"');
  return updatedDescription;
}

function endsWithYouTubeAutoGenerated(text) {
  const target = " Auto-generated by YouTube. ";
  return text.endsWith(target);
}

const sha384 = modules.hash;
const fetch = modules.fetch;
const htmlToText = require("html-to-text");
const encoding = require("encoding");
const delim1 =
  '</div></div></div></div><div class="hwc"><div class="BNeawe tAd8D AP7Wnd"><div><div class="BNeawe tAd8D AP7Wnd">';
const delim2 =
  '</div></div></div></div></div><div><span class="hwc"><div class="BNeawe uEec3 AP7Wnd">';
const url = "https://www.google.com/search?q=";

async function lyricsFinder(e = "", d = "") {
  let i;
  try {
    i = await fetch(`${url}${encodeURIComponent(d + " " + e)}+lyrics`);
    i = await i.textConverted();
    [, i] = i.split(delim1);
    [i] = i.split(delim2);
  } catch (m) {
    try {
      i = await fetch(`${url}${encodeURIComponent(d + " " + e)}+song+lyrics`);
      i = await i.textConverted();
      [, i] = i.split(delim1);
      [i] = i.split(delim2);
    } catch (n) {
      try {
        i = await fetch(`${url}${encodeURIComponent(d + " " + e)}+song`);
        i = await i.textConverted();
        [, i] = i.split(delim1);
        [i] = i.split(delim2);
      } catch (o) {
        try {
          i = await fetch(`${url}${encodeURIComponent(d + " " + e)}`);
          i = await i.textConverted();
          [, i] = i.split(delim1);
          [i] = i.split(delim2);
        } catch (p) {
          i = "";
        }
      }
    }
  }
  const ret = i.split("\n");
  let final = "";
  for (let j = 0; j < ret.length; j += 1) {
    final = `${final}${htmlToText.fromString(ret[j])}\n`;
  }
  return String(encoding.convert(final)).trim();
}

function toObject(arr) {
  var rv = {};
  for (var i = 0; i < arr.length; ++i) if (arr[i] !== undefined) rv[i] = arr[i];
  return rv;
}

function lightOrDark(color) {
  // Variables for red, green, blue values
  var r, g, b, hsp;

  // Check the format of the color, HEX or RGB?
  if (color.match(/^rgb/)) {
    // If RGB --> store the red, green, blue values in separate variables
    color = color.match(
      /^rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*(\d+(?:\.\d+)?))?\)$/
    );

    r = color[1];
    g = color[2];
    b = color[3];
  } else {
    // If hex --> Convert it to RGB: http://gist.github.com/983661
    color = +("0x" + color.slice(1).replace(color.length < 5 && /./g, "$&$&"));

    r = color >> 16;
    g = (color >> 8) & 255;
    b = color & 255;
  }

  // HSP (Highly Sensitive Poo) equation from http://alienryderflex.com/hsp.html
  hsp = Math.sqrt(0.299 * (r * r) + 0.587 * (g * g) + 0.114 * (b * b));

  // Using the HSP value, determine whether the color is light or dark
  if (hsp > 127.5) {
    return "light";
  } else {
    return "dark";
  }
}

function isDntEnabled(req) {
  const dntHeader = req.header("DNT");
  return dntHeader && (dntHeader === "1" || dntHeader === "true");
}

function IsInArray(array, id) {
  for (var i = 0; i < array.length; i++) {
    if (array[i].id === id) return true;
  }
  return false;
}

function getJson(str) {
  try {
    return JSON.parse(str);
  } catch {
    return false;
  }
}

/* support button */
const PATREON_REGEX = /https:\/\/(?:www\.)?patreon\.com\/(?<name>[\w\d_-]+)/;

/* connections */
const TWITTER_REGEX = /https:\/\/(?:www\.)?(?:twitter\.com|x\.com)\/(?<name>[\w\d_-]+)/;
const CORD_REGEX = /https:\/\/(?:www\.)?discord\.gg\/(?<name>[\w\d_-]+)/;
const TWITCH_REGEX = /https:\/\/(?:www\.)?twitch\.tv\/(?<name>[\w\d_-]+)/;
const REDDIT_REGEX = /https:\/\/(?:www\.)?reddit\.com\/r\/(?<name>[\w\d_-]+)/;
const TIKTOK_REGEX = /https:\/\/(?:www\.)?tiktok\.com\/@(?<name>[\w\d_.-]+)/;
const BLUESKY_REGEX = /https:\/\/(?:www\.)?bsky\.app\/profile\/(?<name>[\w\d\.-]+)/;

/* developer */
const GITHUB_REGEX = /https:\/\/(?:www\.)?github\.com\/(?<name>[\w\d_-]+)/;

/* games */
const STEAM_REGEX = /https:\/\/(?:www\.)?steamcommunity\.com\/(?:(?:id)|(?:profiles))\/(?<name>[\w\d_-]+)/;

/* meta software */
const INSTAGRAM_REGEX = /https:\/\/(?:www\.)?instagram\.com\/(?<name>[\w\d_.-]+)/;
const THREADS_BY_INSTAGRAM_REGEX = /https:\/\/(?:www\.)?threads\.net\/@(?<name>[\w\d_.-]+)/;
const FACEBOOK_REGEX = /https:\/\/(?:www\.)?facebook\.com\/(?<name>[\w\d_.-]+)/;

/* creator / media */
const FLOATPLANE_REGEX = /https:\/\/(?:www\.)?floatplane\.com\/channel\/(?<name>[\w\d_-]+)/;

/* music */
const LNKTO_REGEX = /(?:https?:\/\/)?(?:(?<subdomain>[\w-]+)\.)?(?<domain>lnk\.to|ffm\.to)\/(?<path>\S*)/i;
const SOUNDCLOUD_REGEX = /https:\/\/(?:www\.)?soundcloud\.com\/(?<name>[\w\d_-]+)/;

module.exports = function (app, config, renderTemplate) {
 

  app.get("/old", function (req, res) {
    const v = req.query.v;

    renderTemplate(res, req, "poketube-old.ejs", {
      v,
    });
  });
  
app.get("/embed/:v", function (req, res) {
  const v = req.params.v;
  const hostname = req.hostname;

  if (!/^[a-zA-Z0-9_-]{11}$/.test(v)) {
    return res.status(400).send("Invalid video ID");
  }

  renderTemplate(res, req, "embed.ejs", {
    v,
    hostname,
  });
});

  const watchRateLimitCache = new Map();
  const WATCH_LIMIT_WINDOW = 60000;
  const WATCH_MAX_REQUESTS = 60;

  setInterval(() => {
    const now = Date.now();
    for (const [ip, data] of watchRateLimitCache.entries()) {
      if (now - data.firstRequest > WATCH_LIMIT_WINDOW) watchRateLimitCache.delete(ip);
    }
  }, 5 * 60 * 1000);

 app.get("/watch", async (req, res) => {
  const requestEpoch = currentEpoch; // Lock request to current epoch
  const ip = req.headers['x-forwarded-for'] || req.socket.remoteAddress;
  const nowTime = Date.now();
  const userRateInfo = watchRateLimitCache.get(ip) || { count: 0, firstRequest: nowTime };

  if (nowTime - userRateInfo.firstRequest > WATCH_LIMIT_WINDOW) {
    userRateInfo.count = 1;
    userRateInfo.firstRequest = nowTime;
  } else {
    userRateInfo.count++;
    if (userRateInfo.count > WATCH_MAX_REQUESTS) {
      return res.status(429).send("Too Many Requests");
    }
  }
  watchRateLimitCache.set(ip, userRateInfo);

  const { dm, region, hl, v, e, r, f, m, quality: q, a, universe, dyx} = req.query; 

  if (!v) {
    return res.redirect("/");
  }

  const regex = new RegExp("^([a-zA-Z0-9_-]{11})");
  const isMatch = regex.test(v);

  if (!isMatch) {
    res.status(500); 
    res.header('X-Robots-Tag', 'noindex, nofollow');
    return renderTemplate(res, req, "invalid-video.ejs", {
      v,
      err_reason:"not found"
    });
  }
  
  var contentlang = hl || "en-US";
  var contentregion = region || "US";

  const isVideoValid = await INNERTUBE.isvalidvideo(v);
  if (!isVideoValid) {
    res.status(500); 
    res.header('X-Robots-Tag', 'noindex, nofollow');
    return renderTemplate(res, req, "invalid-video.ejs", {
      v,
      err_reason:"not found"
    });
  }

  const u = await media_proxy(v);
  
  // Immediately drop the request if epoch changed during async fetch
  if (currentEpoch !== requestEpoch) {
    return res.status(499).send("Request dropped by server.");
  }

  const secure = ["poketube.fun"].includes(req.hostname);
  const verify = req.hostname === "poketube.sudovanilla.com";

  const officialHost = "poketube.fun";
 
  if (req.hostname !== officialHost && config.invapi.includes("invid-api.poketube.fun")) {
    
    const kaomojis = [
      "(ó﹏ò｡)", 
      "( ｡ •̀ ᴖ •́ ｡)", 
      "(｡>﹏<｡)", 
      "( ´△｀)", 
      "૮( > ﻌ < )ა",
      "( ╥﹏╥ )",
      "(=^-ω-^=)"
    ];
    const randomKaomoji = kaomojis[Math.floor(Math.random() * kaomojis.length)];

    const message = `
      <style>
         @keyframes gradient {
          0% { background-position: 0% 50%; }
          50% { background-position: 100% 50%; }
          100% { background-position: 0% 50%; }
        }

         @keyframes float {
          0% { transform: translateY(0px); }
          50% { transform: translateY(-12px); }
          100% { transform: translateY(0px); }
        }

        body {
          background: linear-gradient(-45deg, #fff0f3, #ffe4e8, #ffcdd2, #fce4ec);
          background-size: 400% 400%;
          animation: gradient 12s ease infinite;
          color: #704c54;
          /* Offline-safe rounded system fonts! */
          font-family: ui-rounded, 'Segoe UI Rounded', 'Nunito', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          margin: 0;
          height: 100vh;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          text-align: center;
          padding: 0 20px;
        }

        .kaomoji {
          font-size: 6rem;
          color: #f080a0;
          margin-bottom: 10px;
          font-weight: 700;
          text-shadow: 0 8px 20px rgba(240, 128, 160, 0.25);
          animation: float 3s ease-in-out infinite;
        }

        h1 { 
          font-size: 2.4rem; 
          color: #e06c8f; 
          margin: 0 0 15px 0;
          font-weight: 700;
          letter-spacing: -0.5px;
        }

        p {
          font-size: 1.15rem;
          max-width: 600px;
          line-height: 1.6;
          margin: 0 0 20px 0;
          font-weight: 500;
        }

        code { 
          background: rgba(255, 255, 255, 0.7); 
          color: #d16b88;
          padding: 4px 10px; 
          border-radius: 10px; 
          font-weight: 700;
          font-size: 1.05rem;
          box-shadow: 0 2px 5px rgba(0,0,0,0.02);
        }

        .button {
          display: inline-block;
          background: #f48fb1;
          color: #ffffff;
          text-decoration: none;
          font-weight: 700;
          font-size: 1.1rem;
          padding: 14px 32px;
          /* Super rounded corners for maximum coziness */
          border-radius: 25px; 
          transition: all 0.3s ease;
          box-shadow: 0 6px 15px rgba(244, 143, 177, 0.35);
          margin-top: 20px;
        }

        .button:hover { 
          background: #f06292;
          transform: translateY(-3px);
          box-shadow: 0 8px 20px rgba(240, 98, 146, 0.4);
        }

        .admin-note {
          margin-top: 40px; 
          font-size: 1rem;
          color: #a38189;
          background: rgba(255, 255, 255, 0.4);
          padding: 18px 30px;
          border-radius: 20px;
          font-weight: 600;
          border: 2px dashed rgba(244, 143, 177, 0.3);
          max-width: 550px;
        }
      </style>

      <div class="kaomoji">${randomKaomoji}</div>
      
      <h1>Uh oh! A tiny configuration hiccup... ☁️</h1>
      
      <p>
        It looks like this custom instance is trying to use the official <code>Poke</code> API endpoint. 
      </p>

      <p>
        <strong>Why is this an issue?</strong> YouTube strictly limits how many videos a single server can request. When multiple sites share the exact same API, the servers quickly get overwhelmed and rate-limited. This causes videos to buffer forever or completely break for everyone! 🥺
      </p>

      <p>
        To keep things running smoothly, every instance needs its own dedicated API. Hosting your own Invidious backend ensures your site runs perfectly without any shared limits or sleepy servers! ✨
      </p>

      <a href="https://docs.invidious.io/installation/" target="_blank" class="button">View the Installation Guide 🌸</a>

      <div class="admin-note">
        <strong>Are you the server admin? 💌</strong> <br>
        Fixing this is a breeze! Just update your <code>config.json</code> with your newly hosted API link, give your server a quick restart, and you'll be good to go. 
      </div>
    `;

    return res.status(500).send(message);
  }
    
  INNERTUBE.getYouTubePlayerInfo(f, v, contentlang, contentregion).then(
    (data) => {
      // Drop immediately if request was issued from a past epoch
      if (currentEpoch !== requestEpoch) {
        return res.status(499).send("Request dropped by server.");
      }

      try {
        const knownErrors = {
          "COPYRIGHT_BLOCKED": "This video contains content from a copyright holder who has blocked it.",
          "UPLOADER_REMOVED": "This video has been removed by the uploader.",
          "VIDEO_UNAVAILABLE": "Video unavailable.",
          "INAPPROPRIATE": "This video may be inappropriate for some users."
        };

        if (data?.error) {
          res.status(500);
          res.header('X-Robots-Tag', 'noindex, nofollow');
          return renderTemplate(res, req, "invalid-video.ejs", {
            v,
            error: true,
            error_message: data.message || "An error occurred",
            knownErrors: knownErrors,
            err_reason: data.reason || data.message
          });
        }
 
        const channel_uploads = data?.channel_uploads;
        const json = data?.json;
        const engagement = data?.engagement;
        const inv_comments = data?.comments || "Disabled";
        const inv_vid = data?.vid;
        const desc = data?.desc || "";

 
        let d = false;
        if (desc !== "[object Object]") {
          d = desc.toString().replace(/\n/g, " <br> ");
        }

        const descriptionString = String(inv_vid?.description).replace(/\bx.com\b/, "twitter.com")

        function extractInfo(regex) {
          return descriptionString !== "[object Object]"
            ? (regex.exec(descriptionString) ?? {}).groups
            : undefined;
        }

        const support = extractInfo(PATREON_REGEX);
        const STUPID_ELON_MUSK_WEBSITE_HE_IS_TRYING_TO_CALL_IT_X_FOR_SOME_REASON_WHICH_IS_A_STUPID_NAME_WE_WILL_FOREVER_CALL_IT_TWITTER_AND_HE_CAN_DO_NOTHING_ABOUT_IT_LOL_FUCK_YOU_ELON_TRANS_RIGHTS_BTW = extractInfo(TWITTER_REGEX);
        const linkto = extractInfo(LNKTO_REGEX);
        const discord = extractInfo(CORD_REGEX);
        const twitch = extractInfo(TWITCH_REGEX);
        const reddit = extractInfo(REDDIT_REGEX);
        const tiktok = extractInfo(TIKTOK_REGEX);
        const github = extractInfo(GITHUB_REGEX);
        const steam = extractInfo(STEAM_REGEX);
        const soundcloud = extractInfo(SOUNDCLOUD_REGEX);
        const floatplane = extractInfo(FLOATPLANE_REGEX);
        const bluesky = extractInfo(BLUESKY_REGEX);
        
        /* meta software */
        const instagram = extractInfo(INSTAGRAM_REGEX);
        const threads_by_instagram = extractInfo(THREADS_BY_INSTAGRAM_REGEX);
        const facebook = extractInfo(FACEBOOK_REGEX);

        const videoObject = inv_vid?.adaptiveFormats;
        function findItag(adaptiveFormats) {
        return;
        }
        
        const itag_hd = findItag(videoObject);
        var proxyurl = config.p_url;
        var vidurl = u.url;
        var isvidious = u.isInvidiousURL;
        var mediaproxy = config.media_proxy;

        if (inv_vid?.genre === "Music") {
          var vidurl = u.losslessurl;
        }

        var vidurl = config.videourl;
        var isvidious = true;

        if (req.useragent.source.includes("Pardus")) {
          var vidurl = "https://iv.ggtyler.dev";
          var mediaproxy = "https://nyc1.pokejan.ggtyler.dev/";
          var isvidious = true;
          var isSchoolProxy = "";
        }

        // unused
        let badges = "";
        let comments = "";
        let nnn = "";

        const dnt_val = isDntEnabled(req);

        if (
          inv_vid?.error ===
            "The uploader has not made this video available in your country" ||
          inv_vid?.error === "This video is not available"
        ) {
          return res.send(
            "error: " + inv_vid.error + " please refresh the page please qt"
          );
        }

        // REMOVED the 404.ejs redirect block so it correctly falls through to watch.ejs!

        var uaos = req.useragent.os;
        const browser = req.useragent.browser;
        const IsOldWindows =
          (uaos === "Windows 7" || uaos === "Windows 8") &&
          browser === "Firefox";

        if (req.query.from === "short") var shortsui = true;

        try {
          
          res.header('X-Robots-Tag', 'noindex, nofollow');
          renderTemplate(res, req, "watch.ejs", {
            color: data?.color,
            color2: data?.color2,
            linkify,
            engagement,
            linkto,
            IsOldWindows,
            channelurlfixer,
            itag_hd,
            facebook,
            support,
            dyx,
            shortsui,
            queryid:v,
            u: vidurl,
            isvidious: isvidious,
            video: json,
            date: inv_vid?.publishedText    ,
            e,
            a,
            twitter:STUPID_ELON_MUSK_WEBSITE_HE_IS_TRYING_TO_CALL_IT_X_FOR_SOME_REASON_WHICH_IS_A_STUPID_NAME_WE_WILL_FOREVER_CALL_IT_TWITTER_AND_HE_CAN_DO_NOTHING_ABOUT_IT_LOL_FUCK_YOU_ELON_TRANS_RIGHTS_BTW,
             dm,
            proxyurl,
            media_proxy_url: mediaproxy,
            instagram,
            useragent: req.useragent,
            config,
            verify,
            discord,
            turntomins,
            twitch,
            github,
            steam,
            tiktok,
            bluesky,
            floatplane,
            soundcloud,
            dnt_val,
            reddit,
            channel_uploads,
            secure,
            process,
            VideoData:inv_vid,
            isSchoolProxy,
            sha384,
            lightOrDark,
            isMobile: req.useragent.isMobile,
            tj: data?.channel,
            r,
            threads:threads_by_instagram,
            hostname:req.hostname,
            qua: q,
            inv: inv_comments,
            convert,
            convertLegacy,
            universe,
            wiki: data?.wiki,
            escapeHtml,
            f,
            t: config.t_url,
            optout: m,
            badges,
            desc,
            comments,
            n: nnn,
            inv_vid,
            lyrics: "",
          });
        } catch (err) {
            res.status(500); 
            res.header('X-Robots-Tag', 'noindex, nofollow');
            renderTemplate(res, req, "video-error.ejs", {
            v,
            err_reason:err
          });
          console.log(err)
        }
      } catch (error) {
        console.error(error);
        return res.redirect(`/watch?v=${req.query.v}&fx=1&err=${error}`);
      }
    }
  ).catch(error => {
     if (currentEpoch !== requestEpoch) {
       return res.status(499).send("Request dropped by server.");
     }
     console.error(error);
     return res.redirect(`/watch?v=${req.query.v}&fx=1&err=${error}`);
  });
});
  
  app.get("/lite", async (req, res) => {
       const { v } = req.query; 

      renderTemplate(res, req, "lite.ejs", {
      videoid:v,
      }); 
  });
 
};