const {
  fetcher,
  INNERTUBE,
  wiki,
  musicInfo,
  modules,
  version,
  initlog,
  init,
} = require("../libpoketube-initsys.js");
const {
  IsJsonString,
  convert,
  getFirstLine,
  capitalizeFirstLetter,
  turntomins,
  getRandomInt,
  escapeHtml,
  getRandomArbitrary,
} = require("../ptutils/libpt-coreutils.js");
const media_proxy = require("../libpoketube-video.js");
const atmos = require("../../../pokeatmosurls.json");
const config = require("../../../config.json");

function linkify(text) {
  // regular expression to match URLs
  const urlRegex = /(https?:\/\/[^\s]+)/g;

  return text.replace(urlRegex, (url) => {
    // wrap the URL in an <a> tag with the URL as the href attribute
    return `<a href="/api/redirect?u=${btoa(
      url
        .replace(/twitter\.com/g, "nitter.net")
        .replace(/reddit\.com/g, "teddit.net")
        .replace("https://youtube.com", "")
        .replace("https://youtu.be", "")
    )}" target="_blank">${url}</a>`;
  });
}

function channelurlfixer(text) {
  // Create a regular expression to match <a> tags with href containing "/channel/"
  const regex = /<a\s+href="\/channel\/([^"]+)"/g;
  // Replace matching <a> tags with the modified href attribute
  const updatedDescription = text.replace(regex, '<a href="/channel?id=$1"');
  return updatedDescription;
}

function endsWithYouTubeAutoGenerated(text) {
  const target = " Auto-generated by YouTube. ";
  return text.endsWith(target);
}

const sha384 = modules.hash;
const fetch = modules.fetch;
const htmlToText = require("html-to-text");
const encoding = require("encoding");
const delim1 =
  '</div></div></div></div><div class="hwc"><div class="BNeawe tAd8D AP7Wnd"><div><div class="BNeawe tAd8D AP7Wnd">';
const delim2 =
  '</div></div></div></div></div><div><span class="hwc"><div class="BNeawe uEec3 AP7Wnd">';
const url = "https://www.google.com/search?q=";

async function lyricsFinder(e = "", d = "") {
  let i;
  try {
    i = await fetch(`${url}${encodeURIComponent(d + " " + e)}+lyrics`);
    i = await i.textConverted();
    [, i] = i.split(delim1);
    [i] = i.split(delim2);
  } catch (m) {
    try {
      i = await fetch(`${url}${encodeURIComponent(d + " " + e)}+song+lyrics`);
      i = await i.textConverted();
      [, i] = i.split(delim1);
      [i] = i.split(delim2);
    } catch (n) {
      try {
        i = await fetch(`${url}${encodeURIComponent(d + " " + e)}+song`);
        i = await i.textConverted();
        [, i] = i.split(delim1);
        [i] = i.split(delim2);
      } catch (o) {
        try {
          i = await fetch(`${url}${encodeURIComponent(d + " " + e)}`);
          i = await i.textConverted();
          [, i] = i.split(delim1);
          [i] = i.split(delim2);
        } catch (p) {
          i = "";
        }
      }
    }
  }
  const ret = i.split("\n");
  let final = "";
  for (let j = 0; j < ret.length; j += 1) {
    final = `${final}${htmlToText.fromString(ret[j])}\n`;
  }
  return String(encoding.convert(final)).trim();
}

function toObject(arr) {
  var rv = {};
  for (var i = 0; i < arr.length; ++i) if (arr[i] !== undefined) rv[i] = arr[i];
  return rv;
}

function lightOrDark(color) {
  // Variables for red, green, blue values
  var r, g, b, hsp;

  // Check the format of the color, HEX or RGB?
  if (color.match(/^rgb/)) {
    // If RGB --> store the red, green, blue values in separate variables
    color = color.match(
      /^rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*(\d+(?:\.\d+)?))?\)$/
    );

    r = color[1];
    g = color[2];
    b = color[3];
  } else {
    // If hex --> Convert it to RGB: http://gist.github.com/983661
    color = +("0x" + color.slice(1).replace(color.length < 5 && /./g, "$&$&"));

    r = color >> 16;
    g = (color >> 8) & 255;
    b = color & 255;
  }

  // HSP (Highly Sensitive Poo) equation from http://alienryderflex.com/hsp.html
  hsp = Math.sqrt(0.299 * (r * r) + 0.587 * (g * g) + 0.114 * (b * b));

  // Using the HSP value, determine whether the color is light or dark
  if (hsp > 127.5) {
    return "light";
  } else {
    return "dark";
  }
}

function isDntEnabled(req) {
  const dntHeader = req.header("DNT");
  return dntHeader && (dntHeader === "1" || dntHeader === "true");
}

function IsInArray(array, id) {
  for (var i = 0; i < array.length; i++) {
    if (array[i].id === id) return true;
  }
  return false;
}

function getJson(str) {
  try {
    return JSON.parse(str);
  } catch {
    return false;
  }
}

/* support button */
const PATREON_REGEX = /https:\/\/(?:www\.)?patreon\.com\/(?<name>[\w\d_-]+)/;

/* connections */
const TWITTER_REGEX = /https:\/\/(?:www\.)?(?:twitter\.com|x\.com)\/(?<name>[\w\d_-]+)/;
const CORD_REGEX = /https:\/\/(?:www\.)?discord\.gg\/(?<name>[\w\d_-]+)/;
const TWITCH_REGEX = /https:\/\/(?:www\.)?twitch\.tv\/(?<name>[\w\d_-]+)/;
const REDDIT_REGEX = /https:\/\/(?:www\.)?reddit\.com\/r\/(?<name>[\w\d_-]+)/;
const TIKTOK_REGEX = /https:\/\/(?:www\.)?tiktok\.com\/@(?<name>[\w\d_.-]+)/;
const BLUESKY_REGEX = /https:\/\/(?:www\.)?bsky\.app\/profile\/(?<name>[\w\d\.-]+)/;

/* developer */
const GITHUB_REGEX = /https:\/\/(?:www\.)?github\.com\/(?<name>[\w\d_-]+)/;

/* games */
const STEAM_REGEX = /https:\/\/(?:www\.)?steamcommunity\.com\/(?:(?:id)|(?:profiles))\/(?<name>[\w\d_-]+)/;

/* meta software */
const INSTAGRAM_REGEX = /https:\/\/(?:www\.)?instagram\.com\/(?<name>[\w\d_.-]+)/;
const THREADS_BY_INSTAGRAM_REGEX = /https:\/\/(?:www\.)?threads\.net\/@(?<name>[\w\d_.-]+)/;
const FACEBOOK_REGEX = /https:\/\/(?:www\.)?facebook\.com\/(?<name>[\w\d_.-]+)/;

/* creator / media */
const FLOATPLANE_REGEX = /https:\/\/(?:www\.)?floatplane\.com\/channel\/(?<name>[\w\d_-]+)/;

/* music */
const LNKTO_REGEX = /https:\/\/(?<subdomain>\w+)\.lnk\.to\/(?<path>\S*)/;
const SOUNDCLOUD_REGEX = /https:\/\/(?:www\.)?soundcloud\.com\/(?<name>[\w\d_-]+)/;

module.exports = function (app, config, renderTemplate) {
  app.get("/encryption", async function (req, res) {
    res.json("error in parsing");
  });

  app.get("/old", function (req, res) {
    const v = req.query.v;

    renderTemplate(res, req, "poketube-old.ejs", {
      v,
    });
  });

  app.get("/watch", async (req, res) => {
    const { dm, region, hl, v, e, r, f, m, quality: q, a, universe, dyx} = req.query; 

    if (!v) {
      return res.redirect("/");
    }

    const regex = new RegExp("^([a-zA-Z0-9_-]{11})");
    const isMatch = regex.test(v);

    if (!isMatch) {
              res.status(500); 
              res.header('X-Robots-Tag', 'noindex, nofollow');
              renderTemplate(res, req, "invalid-video.ejs", {
              v,
              err_reason:"not found"
              });
 }
    
    var contentlang = hl || "en-US";
    var contentregion = region || "US";

    const isVideoValid = await INNERTUBE.isvalidvideo(v);
    if (!isVideoValid) {
   res.status(500); 
              res.header('X-Robots-Tag', 'noindex, nofollow');
              renderTemplate(res, req, "invalid-video.ejs", {
              v,
              err_reason:"not found"
              });
    }

    const u = await media_proxy(v);
    
const secure = ["poketube.fun"].includes(req.hostname);
    const verify = req.hostname === "poketube.sudovanilla.com";

    const officialHost = "poketube.fun";
 
   // Check if the host is unofficial AND they are still using your specific API
   if (req.hostname !== officialHost && config.invapi.includes("invid-api.poketube.fun")) {
    const message = `
      <style>
        body {
          background-color: #fdf2f4;
          background-image: radial-gradient(#ffcdd2 2px, transparent 2px);
          background-size: 30px 30px;
          color: #6a4f55;
          font-family: system-ui, -apple-system, sans-serif;
          margin: 0;
          height: 100vh;
          display: flex;
          align-items: center;
          justify-content: center;
        }
        .error-container {
          background: #ffffff;
          max-width: 550px;
          padding: 50px 40px;
          border-radius: 30px;
          border: 3px solid #ffd1dc;
          box-shadow: 0 12px 40px rgba(255, 182, 193, 0.3);
          text-align: center;
          position: relative;
        }
        .error-code {
          font-size: 4.5rem;
          font-weight: 800;
          color: #ffb6c1;
          margin: 0;
          line-height: 1;
          letter-spacing: -2px;
        }
        .error-badge {
          display: inline-block;
          background: #ffe4e8;
          color: #d16b88;
          padding: 6px 14px;
          border-radius: 20px;
          font-size: 0.85rem;
          font-weight: 700;
          margin-top: 12px;
          margin-bottom: 25px;
          text-transform: uppercase;
          letter-spacing: 1.5px;
        }
        h1 { 
          color: #ff8da1; 
          font-size: 1.6rem; 
          margin-top: 0;
          margin-bottom: 15px;
        }
        p {
          font-size: 1.05rem;
          line-height: 1.6;
          margin-bottom: 20px;
        }
        code { 
          background: #fff0f3; 
          color: #d16b88;
          padding: 4px 8px; 
          border-radius: 8px; 
          font-weight: 600;
        }
        .button {
          display: inline-block;
          background: #ff8da1;
          color: #ffffff;
          text-decoration: none;
          font-weight: 700;
          padding: 14px 28px;
          border-radius: 50px;
          transition: transform 0.2s, background 0.2s;
          box-shadow: 0 4px 15px rgba(255, 141, 161, 0.4);
          margin-top: 10px;
        }
        .button:hover { 
          background: #ff728a;
          transform: translateY(-2px);
        }
        .footer-text {
          margin-top: 35px; 
          color: #b59fa4; 
          font-size: 0.9rem;
          border-top: 2px dashed #ffe4e8;
          padding-top: 20px;
        }
        .kaomoji {
          font-size: 2.5rem;
          color: #ffb6c1;
          margin-bottom: 10px;
          display: block;
        }
      </style>

      <div class="error-container">
        <span class="kaomoji">( > < )</span>
        <div class="error-code">500</div>
        <div class="error-badge">Config Mismatch</div>
        
        <h1>Let's update your API! 🎀</h1>
        
        <p>
          Hi there! It looks like your custom instance is trying to use the official <code>Poke</code> API endpoint.
        </p>

        <p>
          To keep things cozy for everyone, our API is reserved just for the main site. 
          When multiple instances share the same endpoint, the servers get a little sleepy and rate-limit everyone! 🥺
        </p>

        <p>
          Setting up your own Invidious instance is super easy, and it makes sure your site stays fast, happy, and free from shared limits. ✨
        </p>

        <a href="https://docs.invidious.io" target="_blank" class="button">Read the Invidious Docs 🌸</a>

        <div class="footer-text">
          Fixing this is easy peasy! Just update your <code>config.json</code> with your new API, restart your server, and you'll be good to go. 💖
        </div>
      </div>
    `;

    return res.status(500).send(message);
  } 
    
    INNERTUBE.getYouTubePlayerInfo(f, v, contentlang, contentregion).then(
      (data) => {
        try {
           const channel_uploads = data?.channel_uploads;
          const json = data?.json;
          const engagement = data?.engagement;
          const inv_comments = data?.comments || "Disabled";
          const inv_vid = data?.vid;
          const desc = data?.desc || "";

 
          let d = false;
          if (desc !== "[object Object]") {
            d = desc.toString().replace(/\n/g, " <br> ");
          }

          const descriptionString = String(inv_vid?.description).replace(/\bx.com\b/, "twitter.com")

          function extractInfo(regex) {
            return descriptionString !== "[object Object]"
              ? (regex.exec(descriptionString) ?? {}).groups
              : undefined;
          }

          const support = extractInfo(PATREON_REGEX);
          const STUPID_ELON_MUSK_WEBSITE_HE_IS_TRYING_TO_CALL_IT_X_FOR_SOME_REASON_WHICH_IS_A_STUPID_NAME_WE_WILL_FOREVER_CALL_IT_TWITTER_AND_HE_CAN_DO_NOTHING_ABOUT_IT_LOL_FUCK_YOU_ELON_TRANS_RIGHTS_BTW = extractInfo(TWITTER_REGEX);
          const linkto = extractInfo(LNKTO_REGEX);
          const discord = extractInfo(CORD_REGEX);
          const twitch = extractInfo(TWITCH_REGEX);
          const reddit = extractInfo(REDDIT_REGEX);
          const tiktok = extractInfo(TIKTOK_REGEX);
          const github = extractInfo(GITHUB_REGEX);
          const steam = extractInfo(STEAM_REGEX);
          const soundcloud = extractInfo(SOUNDCLOUD_REGEX);
          const floatplane = extractInfo(FLOATPLANE_REGEX);
          const bluesky = extractInfo(BLUESKY_REGEX);
          
          /* meta software */
          const instagram = extractInfo(INSTAGRAM_REGEX);
          const threads_by_instagram = extractInfo(THREADS_BY_INSTAGRAM_REGEX);
         const facebook = extractInfo(FACEBOOK_REGEX);

          const videoObject = inv_vid?.adaptiveFormats;
          function findItag(adaptiveFormats) {
          return;
          }
          
          const itag_hd = findItag(videoObject);
          var proxyurl = config.p_url;
          var vidurl = u.url;
          var isvidious = u.isInvidiousURL;
          var mediaproxy = config.media_proxy;

          if (inv_vid?.genre === "Music") {
            var vidurl = u.losslessurl;
          }

          var vidurl = config.videourl;
          var isvidious = true;

          if (req.useragent.source.includes("Pardus")) {
            var vidurl = "https://iv.ggtyler.dev";
            var mediaproxy = "https://nyc1.pokejan.ggtyler.dev/";
            var isvidious = true;
            var isSchoolProxy = "";
          }

          // unused
          let badges = "";
          let comments = "";
          let nnn = "";

          const dnt_val = isDntEnabled(req);

          if (
            inv_vid?.error ===
              "The uploader has not made this video available in your country" ||
            inv_vid?.error === "This video is not available"
          ) {
            res.send(
              "error: " + inv_vid.error + " please refresh the page please qt"
            );
          }

          if (inv_vid?.error) {
            renderTemplate(res, req, "404.ejs", {
              v,
            });
          }

          var uaos = req.useragent.os;
          const browser = req.useragent.browser;
          const IsOldWindows =
            (uaos === "Windows 7" || uaos === "Windows 8") &&
            browser === "Firefox";

          if (req.query.from === "short") var shortsui = true;

          try {
            
            res.header('X-Robots-Tag', 'noindex, nofollow');
            renderTemplate(res, req, "watch.ejs", {
              color: data?.color,
              color2: data?.color2,
              linkify,
              engagement,
              linkto,
              IsOldWindows,
              channelurlfixer,
              itag_hd,
              facebook,
              support,
              dyx,
              shortsui,
              queryid:v,
              u: vidurl,
              isvidious: isvidious,
              video: json,
              date: inv_vid?.publishedText	,
              e,
              a,
              twitter:STUPID_ELON_MUSK_WEBSITE_HE_IS_TRYING_TO_CALL_IT_X_FOR_SOME_REASON_WHICH_IS_A_STUPID_NAME_WE_WILL_FOREVER_CALL_IT_TWITTER_AND_HE_CAN_DO_NOTHING_ABOUT_IT_LOL_FUCK_YOU_ELON_TRANS_RIGHTS_BTW,
               dm,
              proxyurl,
              media_proxy_url: mediaproxy,
              instagram,
              useragent: req.useragent,
              config,
              verify,
              discord,
              turntomins,
              twitch,
              github,
              steam,
              tiktok,
              bluesky,
              floatplane,
              soundcloud,
              dnt_val,
              reddit,
              channel_uploads,
              secure,
              process,
              VideoData:inv_vid,
              isSchoolProxy,
              sha384,
              lightOrDark,
              isMobile: req.useragent.isMobile,
              tj: data?.channel,
              r,
              threads:threads_by_instagram,
              hostname:req.hostname,
              qua: q,
              inv: inv_comments,
              convert,
              universe,
              wiki: data?.wiki,
              escapeHtml,
              f,
              t: config.t_url,
              optout: m,
              badges,
              desc,
              comments,
              n: nnn,
              inv_vid,
              lyrics: "",
            });
          } catch (err) {
              res.status(500); 
              res.header('X-Robots-Tag', 'noindex, nofollow');
              renderTemplate(res, req, "video-error.ejs", {
              v,
              err_reason:err
            });
            console.log(err)
          }
        } catch (error) {
          console.error(error);
          return res.redirect(`/watch?v=${req.query.v}&fx=1&err=${error}`);
        }
      }
    );
  });

  app.get("/lite", async (req, res) => {
       const { dm, region, hl, v, e, r, f, m, quality: q, a, universe, } = req.query; 

            renderTemplate(res, req, "lite.ejs", {
            videoid:v,
            });
        
  });
 
};
